"""Init

Revision ID: c195987437c4
Revises: 2c58be2a640b
Create Date: 2024-04-14 17:09:16.558595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c195987437c4'
down_revision: Union[str, None] = '2c58be2a640b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'grade',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'grade_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('students', sa.Column('fullname', sa.String(length=150), nullable=False))
    op.drop_column('students', 'full_name')
    op.add_column('teachers', sa.Column('fullname', sa.String(length=150), nullable=False))
    op.drop_column('teachers', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'fullname')
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_column('students', 'fullname')
    op.alter_column('grades', 'grade_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('grades', 'grade',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
